name    : "mobileone-s3"
channels: 3
backbone: [
  # [from, number, module,              args(out_channels, ...)]
  [-1,     1,      MobileOneBlock,      [64, 3, 2, 1, 1, 1, True, "zeros", None, None, True, False, 1]],  # 0
  [-1,     1,      MobileOneStage,      [128,  2,  0, True, 1]],                                          # 1
  [-1,     1,      MobileOneStage,      [320,  8,  0, True, 1]],                                          # 2
  [-1,     1,      MobileOneStage,      [768,  10, 0, True, 1]],                                          # 3
  [-1,     1,      MobileOneStage,      [2048, 1,  0, True, 1]],                                          # 4
]
head    : [
  [-1,     1,      MobileOneClassifier, [1024]],                                                          # 5
]
