name    : "mobileone-s0"
channels: 3
backbone: [
  # [from, number, module,              args(out_channels, ...)]
  [-1,     1,      MobileOneBlock,      [48, 3, 2, 1, 1, 1, True, "zeros", None, None, True, False, 1]],  # 0
  [-1,     1,      MobileOneStage,      [48,   2,  0, True, 4]],                                          # 1
  [-1,     1,      MobileOneStage,      [128,  8,  0, True, 4]],                                          # 2
  [-1,     1,      MobileOneStage,      [256,  10, 0, True, 4]],                                          # 3
  [-1,     1,      MobileOneStage,      [1024, 1,  0, True, 4]],                                          # 4
]
head    : [
  [-1,     1,      MobileOneClassifier, [1024]],                                                          # 5
]
