name    : "mobileone-s4"
channels: 3
backbone: [
  # [from, number, module,              args(out_channels, ...)]
  [-1,     1,      MobileOneBlock,      [64, 3, 2, 1, 1, 1, True, "zeros", None, None, True, True, 1]],   # 0
  [-1,     1,      MobileOneStage,      [192,  2,  0, True, 1]],                                          # 1
  [-1,     1,      MobileOneStage,      [448,  8,  0, True, 1]],                                          # 2
  [-1,     1,      MobileOneStage,      [896,  10, 5, True, 1]],                                          # 3
  [-1,     1,      MobileOneStage,      [2048, 1,  1, True, 1]],                                          # 4
]
head    : [
  [-1,     1,      MobileOneClassifier, [1024]],                                                          # 5
]
